services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:///usr/src/app/src/database/database.sqlite
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./src/database:/usr/src/app/src/database
